spring:
  application:
    name : eureka-zuul
server:
  port : 7000

eureka:
  client:
    service-url:
      defaultZone : http://localhost:9000/eureka/

zuul:
  routes:
    eureka-admin :
      path : /admin/**
      serviceId : eureka-admin

    eureka-diary:
      path: /diary/**
      serviceId: eureka-diary

