server:
  port: 9002

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/

feign:  #开启熔断保护
  hystrix:
    enabled: true

spring:
  application:
    name: eureka-diary
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/smartconstruction?serverTimezone=UTC&useSSL=true
    username: root
    password: root
    #url: jdbc:mysql://134.175.21.43:3306/construction?serverTimezone=UTC&useSSL=true
    #username: construction
    #password: construction
  thymeleaf:
      prefix: classpath:/templates/ # 访问template下的html文件需要配置模板，映射
      cache: false # 开发时关闭缓存,不然没法看到实时页面
  servlet:
      multipart:
        max-file-size: 30MB #SpringBoot默认上传文件大小不能超过1MB
        max-request-size: 30MB

mybatis:
  configuration:
    logImpl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.bwsk.entity

logging:
  level:
    com.bwsk: DEBUG
  file:
    path: ./logs